export class Symbol {
  constructor(id, name, emoji) {
    this.id = id;
    this.name = name;
    this.emoji = emoji;
  }
}

export const symbols = [
  new Symbol(1, "Star", "⭐"),
  new Symbol(2, "Heart", "❤️"),
  new Symbol(3, "Circle", "⚫"),
  new Symbol(4, "Triangle", "🔺"),
  new Symbol(5, "Square", "🟦"),
  new Symbol(6, "Diamond", "💎"),
  new Symbol(7, "Lightning", "⚡"),
  new Symbol(8, "Music", "🎵"),
  new Symbol(9, "Sun", "☀️"),
  new Symbol(10, "Moon", "🌙"),
  new Symbol(11, "Cloud", "☁️"),
  new Symbol(12, "Rainbow", "🌈"),
  new Symbol(13, "Apple", "🍎"),
  new Symbol(14, "Banana", "🍌"),
  new Symbol(15, "Cherry", "🍒"),
  new Symbol(16, "Grapes", "🍇"),
  new Symbol(17, "Watermelon", "🍉"),
  new Symbol(18, "Pineapple", "🍍"),
  new Symbol(19, "Strawberry", "🍓"),
  new Symbol(20, "Pizza", "🍕"),
  new Symbol(21, "Hamburger", "🍔"),
  new Symbol(22, "Hotdog", "🌭"),
  new Symbol(23, "Fries", "🍟"),
  new Symbol(24, "Ice Cream", "🍦"),
  new Symbol(25, "Cake", "🍰"),
  new Symbol(26, "Cookie", "🍪"),
  new Symbol(27, "Chocolate", "🍫"),
  new Symbol(28, "Lollipop", "🍭"),
  new Symbol(29, "Candy", "🍬"),
  new Symbol(30, "Popcorn", "🍿"),
  new Symbol(31, "Tea", "🍵"),
  new Symbol(32, "Coffee", "☕"),
  new Symbol(33, "Beer", "🍺"),
  new Symbol(34, "Wine", "🍷"),
  new Symbol(35, "Cocktail", "🍸"),
  new Symbol(36, "Tropical Drink", "🍹"),
  new Symbol(37, "Guitar", "🎸"),
  new Symbol(38, "Drum", "🥁"),
  new Symbol(39, "Microphone", "🎤"),
  new Symbol(40, "Headphones", "🎧"),
  new Symbol(41, "Keyboard", "🎹"),
  new Symbol(42, "Trumpet", "🎺"),
  new Symbol(43, "Saxophone", "🎷"),
  new Symbol(44, "Violin", "🎻"),
  new Symbol(45, "Waves", "🌊"),
  new Symbol(46, "Anchor", "⚓"),
  new Symbol(47, "Ship", "🚢"),
  new Symbol(48, "Airplane", "✈️"),
  new Symbol(49, "Rocket", "🚀"),
  new Symbol(50, "Car", "🚗"),
];
